### ISSUE TITLE
wikipedia数据集title列

### ISSUE THREAD

**Issue by CanvaChen** [pleisto/yuren-13b#2]
pleisto/wikipedia-cn-20230720-filtered 数据集只有source和completion两列，而原始的wikipedia数据集是有title列的，我想要包含titile的数据集。请问有现成的数据吗？或者有现成的脚本可以补充这一列吗？

**Comment by 0xDing** [comment]
> pleisto/wikipedia-cn-20230720-filtered 数据集只有source和completion两列，而原始的wikipedia数据集是有title列的，我想要包含titile的数据集。请问有现成的数据吗？或者有现成的脚本可以补充这一列吗？

因为训练中没用到，所以在清洗时洗掉了。可能只能通过重新清洗来获取，原始的wikipedia数据集在 https://dumps.wikimedia.org/zhwiki/ 可以找到。 我们的清洗脚本暂时不方便公开，但是清洗脚本在开发时的思路是参考了这个开源项目 https://github.com/quqixun/ReadWiki-ZH。 建议考虑直接使用该开源项目来转为markdown，然后再做进一步处理。
